<?php
declare(strict_types=1);

// RickAndMorty SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RickAndMortyUtility::setRegistrar(function (RickAndMortyUtility $u): void {
    $u->clean = [RickAndMortyClean::class, 'call'];
    $u->done = [RickAndMortyDone::class, 'call'];
    $u->make_error = [RickAndMortyMakeError::class, 'call'];
    $u->feature_add = [RickAndMortyFeatureAdd::class, 'call'];
    $u->feature_hook = [RickAndMortyFeatureHook::class, 'call'];
    $u->feature_init = [RickAndMortyFeatureInit::class, 'call'];
    $u->fetcher = [RickAndMortyFetcher::class, 'call'];
    $u->make_fetch_def = [RickAndMortyMakeFetchDef::class, 'call'];
    $u->make_context = [RickAndMortyMakeContext::class, 'call'];
    $u->make_options = [RickAndMortyMakeOptions::class, 'call'];
    $u->make_request = [RickAndMortyMakeRequest::class, 'call'];
    $u->make_response = [RickAndMortyMakeResponse::class, 'call'];
    $u->make_result = [RickAndMortyMakeResult::class, 'call'];
    $u->make_point = [RickAndMortyMakePoint::class, 'call'];
    $u->make_spec = [RickAndMortyMakeSpec::class, 'call'];
    $u->make_url = [RickAndMortyMakeUrl::class, 'call'];
    $u->param = [RickAndMortyParam::class, 'call'];
    $u->prepare_auth = [RickAndMortyPrepareAuth::class, 'call'];
    $u->prepare_body = [RickAndMortyPrepareBody::class, 'call'];
    $u->prepare_headers = [RickAndMortyPrepareHeaders::class, 'call'];
    $u->prepare_method = [RickAndMortyPrepareMethod::class, 'call'];
    $u->prepare_params = [RickAndMortyPrepareParams::class, 'call'];
    $u->prepare_path = [RickAndMortyPreparePath::class, 'call'];
    $u->prepare_query = [RickAndMortyPrepareQuery::class, 'call'];
    $u->graphql_body = [RickAndMortyGraphql::class, 'body'];
    $u->graphql_errors = [RickAndMortyGraphql::class, 'errors'];
    $u->result_basic = [RickAndMortyResultBasic::class, 'call'];
    $u->result_body = [RickAndMortyResultBody::class, 'call'];
    $u->result_headers = [RickAndMortyResultHeaders::class, 'call'];
    $u->transform_request = [RickAndMortyTransformRequest::class, 'call'];
    $u->transform_response = [RickAndMortyTransformResponse::class, 'call'];
});
